### ISSUE TITLE
Execute from main.py

### ISSUE THREAD

**Issue by RiLeone** [RiLeone/warbot#11]
**Is your feature request related to a problem? Please describe.**
So far a `main.py` is provided but it is empty.

**Describe the solution you'd like**
Content of `main.py` should be implemented so to run a game, visualise history and compute stats for a specified world (either by command line argument parsing or some other way). A new folder called `worlds` should be created; this folder should contain subfolders for each playable world (e.g. Switzerland, Debugworld, etc.); the script should walk the directory and return the possibilities to the user which can select one of the worlds (provide a default); upon confirmation the script simulator starts.

**Comment by SGE-MagHead** [comment]
Whe should also think what GUI/Visualisation package to use, if we standardize on it, is going to be easier to merge stuff together

**Comment by RiLeone** [comment]
Indeed @SGE-MagHead, if you have any suggestions, please go ahead and add them here so that we can keep track of this

**Comment by bdaawg** [comment]
@SGE-MagHead are you taking care of visualisation currently?

**Comment by RiLeone** [comment]
Basic functionalities have been implemented, but issue is far from complete. Set it back to "To do".

**Comment by mafilipp** [comment]
What do you think about using flask? Flask is a framework for creating webpages. It is an easy way to get warbot online. In the future we could deploy it on a server, and anyone could access it from the internet. In this way anyone who wants to play does not need to install all the python's package etc but just access the game from a link.
I will create in the next days a PR so that you can evaluate it.
